import type { Metadata } from "next";
import Navbar from "@/components/ui/navbar";

export const metadata: Metadata = {
  title: "Lampros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body suppressHydrationWarning={true}>
      <Navbar />
      {children}
      {/* <Footer /> */}
    </body>
  );
}
