import type { Metadata } from "next";
import { Header } from "@/components/Landing/header/Header";
import { Footer } from "@/components/Landing/footer/Footer";

export const metadata: Metadata = {
  title: "Lampros",
  description: "Generated by create next app",
};

export default function ProfessionalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body suppressHydrationWarning={true}>
      <Header />
      {children}
      <Footer />
    </body>
  );
}
